- name: Git config for work
  shell: |
    git config --global user.name "Boyan Soubachov"
    git config --global user.email "bsoubachov@atlassian.com"
- pip:
    name: cloudtoken
- name: Setup cloudtoken
  shell: |
    cloudtoken --init
    cp atlassian_cloudtoken_config.yaml ~/.config/cloudtoken/config.yaml

- name: Brew taps
  shell: |
    brew tap adoptopenjdk/openjdk
    brew tap --force-auto-update atlassian/kubetoken ssh://git@stash.atlassian.com:7997/kube/homebrew-kubetoken.git
- homebrew_cask:
    name: adoptopenjdk11,adoptopenjdk8
- homebrew:
    name: kubectl,kubetoken
