- name: Git config for work
  shell: |
    git config --global user.name "Boyan Soubachov"
    git config --global user.email "bsoubachov@atlassian.com"
- pip:
    name: cloudtoken
- name: Setup cloudtoken
  shell: |
    cloudtoken --init
    cp atlassian_cloudtoken_config.yaml ~/.config/cloudtoken/config.yaml

- name: Brew tap adoptopenjdk
  shell: brew tap adoptopenjdk/openjdk
- homebrew_cask:
    name: adoptopenjdk11,adoptopenjdk8

